#!/bin/bash

# Imprime texto pantalla
echo "Hello World! :)"

# Lista el contenido del directorio actual
ls

# Crea un directorio
mkdir Test

# Cambia al directorio Test
cd Test

# Lista el contenido del directorio Test
ls
